### ISSUE TITLE
Why not using AloopOutputNode?

### ISSUE THREAD

**Issue by Da-LiFe** [pyjamasam/snips-respeakerd#1]
I had a look at your project. Thanks for sharing!

I'm just wondering why you are not using "AloopOutputNode" to stream the audio to a loopback device. This way, snips-audio-server could be redirected to this loopback (`/usr/bin/snips-audio-server --alsa-capture hw:Loopback,1,0`) and continue streaming the audio to MQTT (which could be removed from this code) and provide audio output (a feature which seems not yet to be integrated in our code).

I made a small prototype on my system at home and it seems to work fine so far. If you are interessted, I could provide a fork/pull-request....

**Comment by sskorol** [comment]
@Da-LiFe hi, just wondering how did you manage to configure loopback? I tried to follow the [official sample](http://respeaker.io/librespeaker_doc/alsa_aloop_test_8cc-example.html), but there's no sound recorded at all. Output file is created, but w/ silence only. Any thoughts?

**Comment by pyjamasam** [comment]
So this code is OLD now (especially since Snips no longer is a public api/sdk after the sonos acquisition), but the original intent was to reduce the number of moving parts.  I wanted a nice clean pipeline in from the respeaker mic array with support for the DOA stuff that it does using closed source libraries.

I also was trying to reduce the number of audio "bits" (pulse, alsa, etc) so that again I had a simpler setup to debug and work with.

I am not really doing anything with this project any more now that snips is gone, but I left the repository here for people to reference incase they needed to do something similar with the respeaker libraries.
